apiVersion: apps/v1
kind: Deployment
metadata:
  # namespace: pingpong
  name: pingpong-dep
spec:
  replicas: 1
  selector:
    matchLabels:
      app: pingpong
  template:
    metadata:
      labels:
        app: pingpong
    spec:
      containers:
        - name: pingpong
          image: mobporo/pingpong:2.075
          envFrom:
            - secretRef:
                name: db-password
          env:
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: db-password
                  key: POSTGRES_PASSWORD


