apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: db-stset
  namespace: project
spec:
  serviceName: db-svc
  replicas: 1
  selector:
    matchLabels:
      app: db
  template:
    metadata:
      labels:
        app: db
    spec:
      containers:
        - name: db
          image: postgres:latest
          ports:
            - name: web
              containerPort: 5432
          volumeMounts:
            - name: db-storage
              mountPath: /data 
          envFrom:
            - secretRef:
                name: db-password
  volumeClaimTemplates:
    - metadata:
        name: db-storage
      spec:
        accessModes: ["ReadWriteOnce"]
        storageClassName: local-path
        resources:
          requests:
            storage: 100Mi